#define KNEE_ORIENTATION        ">>"
#define MAX_LINEAR_VELOCITY_X   0.5
#define MAX_LINEAR_VELOCITY_Y   0.25
#define MAX_ANGULAR_VELOCITY_Z  1.0
#define MAX_THETA               0.35
#define SWING_HEIGHT            0.04
#define STANCE_DEPTH            0.00
#define MAX_STEP_LENGTH         0.11
#define NOMINAL_HEIGHT          0.20